<?php

namespace HomebunkBundle\Repository;

/**
 * HomeTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
